node{
stage('SCM Chechout'){
git https://github.com/SerhiiRomanuik/NotJava
}
stage('Compile-Package')
  //Get maven gome path
def mvnHome = tool name: 'Default', type: 'maven'
  sh "${mvnHome}/bin/mvn package"
}
}
